# Generated by Django 5.0.4 on 2024-04-16 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Investement_type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("decsription", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Stocks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=50, unique=True)),
                ("company_name", models.CharField(max_length=50)),
                ("comppany_description", models.TextField()),
                ("city", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=50)),
                ("cap_typd", models.CharField(max_length=50)),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data.sector"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stock_Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("open", models.FloatField()),
                ("close", models.FloatField()),
                ("high", models.FloatField()),
                ("low", models.FloatField()),
                ("volume", models.IntegerField()),
                (
                    "ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data.stocks"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Shareholder_Patterns",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shareholder_type", models.CharField(max_length=50)),
                ("month", models.IntegerField()),
                ("year", models.IntegerField()),
                ("pct_holdings", models.FloatField()),
                (
                    "ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data.stocks"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fundamental_Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("revenue", models.FloatField()),
                ("cost", models.FloatField()),
                ("tax", models.FloatField()),
                ("asset", models.FloatField()),
                ("debt", models.FloatField()),
                ("profit_after_tax", models.FloatField()),
                ("total_share_outstanding", models.IntegerField()),
                ("earninbgs_per_share", models.FloatField()),
                ("book_value", models.FloatField()),
                ("price", models.FloatField()),
                ("date", models.DateField()),
                ("operating_cost", models.FloatField()),
                (
                    "ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data.stocks"
                    ),
                ),
            ],
        ),
    ]
