# Generated by Django 5.0.4 on 2024-04-17 07:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Investement_type",
            new_name="Investement_Types",
        ),
    ]
